CREATE DATABASE IF NOT EXISTS CATALOGO_MUSICAL;
-- CRIANDO ATABELA CD (ENTIDADE FORTE)
CREATE TABLE CD (
	id_cd INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    gravador VARCHAR(100) NOT NULL,
    data_ date
);

CREATE TABLE cantor(
	id_cantor INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    bibliografia VARCHAR(255)
);

